### ISSUE TITLE
Completions in bash not working properly for erdtree 2.0.0 

### ISSUE THREAD

**Issue by p0kR** [solidiquis/erdtree#150]
It seems, that using `erd --completions bash` outputs code for a tool called `et`, instead of `erd`.
This fits to the screenshot in the README for the completions topic.

For me, after instralliung erdtree, only `erd`, but no command `et` is available after installing erdtree using cargo.

Operating System:
- Pop!_OS 22.04 LTS

SW versions:
- erdtree: 2.0.0
- cargo: 1.69.0

**Comment by solidiquis** [comment]
Yes this was resolved here https://github.com/solidiquis/erdtree/commit/c4ff0dacb137f1007af27f692f1e5ee66bf47cb6

I'll ship a new release tonight or tomorrow addressing the issue :]

**Comment by grawlinson** [comment]
Yo! Package maintainer for Arch Linux here, I've tried cherry picking that commit on top of 2.0.0 and completion still doesn't work (tested with bash/zsh).

**Comment by solidiquis** [comment]
Will have a fix shipped for this tomorrow! Away from my computer for a wee bit

**Comment by Yarden-zamir** [comment]
Ping 👉👈

**Comment by solidiquis** [comment]
Hello all—sorry for the delay. Had a lot of personal matters to tend to this past weekend but just wanted to provide a small update: The `HEAD` of `master` has the fix for this, however, I don't plan to have a new release until later in the week.

**Comment by nmutalik** [comment]
FYI my temporary fix was to rename the executable from `erd` to `et`, since the problem is right now the binary (`erd`) doesn't match the completions generated (`_et`)

**Comment by solidiquis** [comment]
@nmutalik closed by c4ff0dacb137f1007af27f692f1e5ee66bf47cb6

v3.0 release will be out tonight with the fix.

**Comment by yermulnik** [comment]
Should I open new issue for the below?
```shell
> erd --version
erdtree 3.0.0

> source <(erd --completions bash)
error: unexpected argument '--inverted' found

  note: to pass '--inverted' as a value, use '-- --inverted'

Usage: -- [OPTIONS] [DIR]

For more information, try '--help'.
```

**Comment by solidiquis** [comment]
@yermulnik are you using `--inverted` in your config file by chance?

**Comment by yermulnik** [comment]
@solidiquis Oh, my bad, I didn't think to check config file. Yep `--inverted` is indeed there. Though has this flag been deprecated or something like that? Not seeing this in `3.0.0` release notes nor in CHANGELOG 🤔 Should I remove this config option now? Thanks.

**Comment by solidiquis** [comment]
@yermulnik not that's my bad I forgot to mention that. To do the inverted layout you'll now use `--layout inverted` or `-y inverted`.

**Comment by yermulnik** [comment]
@solidiquis No worries and thanks for the pointer 👍🏻

**Comment by jwbowen** [comment]
@solidiquis It took me a bit to figure out the change from `--inverted` to `--layout inverted`. Could you add a note to the release notes to help others find it more quickly?
